export const N=36;
export const names=['Grassland','Meadow','Temperate Forest','Rainforest','Taiga','Savanna','Desert','Dunes','Badlands','Canyon','Rocky Highlands','Mountains','Snow Peaks','Tundra','Glacier','Wetlands','Mangroves','Beach','Shallow Water','Deep Ocean'];
export const descriptions=['Open plains that green with rain and dry into savanna.','Flowering grass and fertile, moisture-rich soil.','Broadleaf woodland thriving in mild, wet climates.','Dense tropical canopy sustained by warmth and rain.','Cold conifer forest bordering the tundra.','Warm grassland with scattered trees.','Dry sandy ground with very little plant cover.','Wind-shaped ridges of desert sand.','Weathered clay hills with sparse vegetation.','Sandstone walls around a central ravine.','Exposed stone and rugged foothills.','Rocky summits that collect snow in cold weather.','Alpine peaks crowned with snow and ice.','Cold open ground with low-growing plants.','Faceted ice that melts in a warmer climate.','Waterlogged ground with tall reeds.','Coastal woodland in warm, wet conditions.','Sandy shore between land and sea.','Sunlit coastal water above the shelf.','Dark open water beyond the shore.'];
export const elevations=[3,3,4,3,5,4,4,5,6,7,9,14,18,8,10,1,1,0,-2,-8];
export function random(seed){let s=seed>>>0;return()=>{s+=0x6D2B79F5;let t=s;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296;};}
export function generate(seed){const r=random(seed);const centers=names.map((_,id)=>({x:3+(id%5)*7+r()*2,z:3+Math.floor(id/5)*8+r()*2,id}));return Array.from({length:N*N},(_,i)=>{const x=i%N,z=Math.floor(i/N);const c=centers.reduce((best,c)=>{const d=(x-c.x)**2+(z-c.z)**2+7*Math.sin(x*.6+c.id)*Math.cos(z*.5);return d<best.d?{...c,d}:best;},{d:Infinity});return {type:c.id,moisture:[.55,.65,.65,.85,.55,.3,.1,.1,.15,.2,.25,.3,.4,.3,.5,.9,.85,.35,1,1][c.id],elevation:elevations[c.id],age:0};});}
export function visibleType(t,sea){if(t.elevation<sea)return t.elevation<sea-4?19:18;return t.type;}
export function step(world,climate,day){let changes=0;const season=Math.sin(day/120*Math.PI*2)*7;world.forEach((t,i)=>{t.age++;if(t.type>=17)return;const temp=climate.temperature+season-t.elevation*.45;const target=Math.max(0,Math.min(1,climate.rain/100-(temp-18)*.008));t.moisture+=(target-t.moisture)*.035;if(t.age<10||((i+day)%7)!==0)return;let next=t.type;if([0,1,2,3,4,5,6,13,15,16].includes(t.type)){if(temp<0)next=13;else if(t.moisture<.20)next=6;else if(t.moisture<.36)next=5;else if(t.moisture>.78&&t.elevation<=1)next=temp>20?16:15;else if(t.moisture>.66)next=temp>24?3:temp<10?4:2;else next=t.moisture>.52?1:0;}if(t.type===11&&temp<1)next=12;if(t.type===12&&temp>6)next=11;if(t.type===14&&temp>7)next=10;if(next!==t.type){t.type=next;t.age=0;changes++;}});return changes;}
export function validateSave(s){return s?.version===1&&Number.isInteger(s.seed)&&Number.isInteger(s.day)&&s.day>=0&&s.climate&&Number.isFinite(s.climate.temperature)&&s.climate.temperature>=-20&&s.climate.temperature<=45&&Number.isFinite(s.climate.rain)&&s.climate.rain>=0&&s.climate.rain<=100&&Number.isFinite(s.climate.sea)&&s.climate.sea>=-5&&s.climate.sea<=8&&Array.isArray(s.world)&&s.world.length===N*N&&s.world.every(t=>Number.isInteger(t.type)&&t.type>=0&&t.type<20&&Number.isFinite(t.moisture)&&t.moisture>=0&&t.moisture<=1&&Number.isFinite(t.elevation)&&Number.isInteger(t.age)&&t.age>=0);}
