import {SEASONS,seasonFor,activeHoliday} from './seasons.js';
import {calendarHTML} from './season-ui.js';
import {renderHistoryChart,handleChartClick,installChartInteractions} from './history-charts.js';
import {renderNewspaper} from './newspaper.js';
import {createMayorUI} from './mayor-ui.js';
import {City,createState,validateSave,capacity} from './simulation.js';
import {World} from './world.js';
import {N,SAVE_KEY,ZONES,SERVICES,MODES,INDUSTRIES,OVERLAYS,MILESTONES,EVENTS,DIFFICULTIES,DISTRICTS,clamp,money} from './data.js';
import {footprint,parcelOf,parcelXY,parcelPrice,canBuy,owned,districtOf,densityGate,PARCEL,PARCELS} from './region.js';
import {PROJECTS,SCENARIOS,requests,currentEvent,respondOffer} from './campaign.js';
import {xy,index,lineCells,rectCells,roadAt} from './network.js';
import {STYLES} from './legacy/catalog.js';
const $=id=>document.getElementById(id);
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.round(n||0).toLocaleString('en-US'),pct=n=>Math.round(clamp(n)*100)+'%';
let toastTimer;
function toast(message){if(!message)return;$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4600);}
function toggleInterface(){immersive=!immersive;if(immersive){setTool('inspect');world.setHover([]);}document.body.classList.toggle('immersive',immersive);$('show-interface').hidden=!immersive;}
async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{toast('Full screen is unavailable here. Press H for a clear city view.');}}
const city=new City(toast);
let world,category='inspect',tool='inspect',density=1,selected=-1,dragStart=-1,hovered=-1,routeMode='bus',routeStops=[],routeName='',lastUI=-1,ready=false,touchStart=null,immersive=false,deleteLayer='all',selectedParcel=17,lastCelebration='';
const categories=[['inspect','⌖','Inspect'],['zones','▦','Housing'],['roads','⌁','Networks'],['services','✚','Services'],['recreation','☀','Recreation'],['decorations','✿','Decorations'],['calendar','▦','Seasons'],['transit','⇄','Transport'],['terrain','♧','Terrain'],['overlays','◈','Overlays'],['land','⊞','Region'],['newspaper','▤','Newspaper'],['projects','☆','Mayor’s Agenda'],['budget','$','Budget'],['delete','⌫','Delete']];
const networkTools={road:{name:'Street',icon:'━',cost:65,days:1,desc:'1 day to build. 65 cars / month. Carries water and power.'},avenue:{name:'Avenue',icon:'═',cost:160,days:2,desc:'2 days to build. 180 cars / month. Faster, higher capacity.'},rail:{name:'Railway',icon:'╫',cost:110,days:7,desc:'7 days to build. Passenger trains and regional freight.'},powerline:{name:'Power line',icon:'ϟ',cost:20,days:3,desc:'3 days to build. Extends the electricity network.'},pipe:{name:'Water pipe',icon:'≈',cost:15,days:2,desc:'2 days to build. Extends the water network.'},bulldoze:{name:'Delete',icon:'⌫',cost:0,desc:'Clear buildings, zoning and networks. Deletion is free.'}};
const terrainTools={raise:{name:'Raise land',icon:'↟',cost:60},lower:{name:'Lower land',icon:'↡',cost:60},flatten:{name:'Level land',icon:'▱',cost:60},forest:{name:'Plant woodland',icon:'♧',cost:35}};
function row(label,value,cls=''){return `<div class="metric-row"><span>${label}</span><b class="${cls}">${value}</b></div>`;}
function meter(label,value,color='#739567'){return `${row(label,pct(value))}<div class="meter"><i style="width:${clamp(value)*100}%;background:${color}"></i></div>`;}
function title(eyebrow,name,desc=''){return `<span class="eyebrow">${eyebrow}</span><div class="section-top"><h3>${name}</h3></div>${desc?`<p>${desc}</p>`:''}`;}
function toolCard(key,name,icon,cost,note=''){return `<button class="tool-card ${tool===key?'active':''}" data-tool="${key}"><span class="tool-symbol">${icon}</span><span><strong>${name}</strong><small>${money(cost)} ${note||'/ tile'}</small></span></button>`;}
function range(key,label,value,min,max,step=1,suffix='%'){return `<label class="field"><span class="field-heading"><span>${label}</span><output>${value}${suffix}</output></span><input type="range" data-setting="${key}" aria-label="${label}" min="${min}" max="${max}" step="${step}" value="${value}"></label>`;}
function district(i){const {x,z}=xy(i);return `${DISTRICTS[districtOf(city.s,i)].name} · ${x+1}, ${z+1}`;}
function setTool(next){tool=next;if(next!=='route')routeStops=[];world.routeDraft=routeStops;world.revision=-1;renderTools();renderDock();$('tool-hint').textContent=tool==='inspect'?'Click any building for its story · Right drag to pan · Scroll to zoom':tool==='route'?'Click road tiles in stopping order · Finish the line in the Transport panel':ZONES[tool]?'Drag a rectangle to zone · Lots need a street on one side · Esc to inspect':SERVICES[tool]?.decoration?'Click clear owned land to decorate · No road or utilities needed':SERVICES[tool]?'Click a clear lot beside a road · Scroll to zoom':tool==='bulldoze'?'Drag to clear tiles · Ctrl+Z undoes construction until the month ends':'Drag to build · Right drag to pan · Esc to inspect';}
function setCategory(next){const wasOpen=!$('tool-panel').hidden&&category===next;category=next;$('inspector').hidden=true;if(next==='calendar'){setTool('inspect');$('tool-panel').hidden=true;showModal(calendarHTML(city.s));}else if(next==='newspaper'){setTool('inspect');$('tool-panel').hidden=true;showModal(renderNewspaper(city.s,escape));}else if(next==='land'||next==='projects'){setTool('inspect');$('tool-panel').hidden=true;next==='land'?renderRegion():renderProjects();}else if(next==='inspect'){setTool('inspect');$('tool-panel').hidden=true;}else if(next==='budget'){setTool('inspect');$('tool-panel').hidden=true;renderBudget();}else {if(next==='zones')setTool('residential');else if(next==='roads')setTool('road');else if(next==='services')setTool('power');else if(next==='recreation')setTool('park');else if(next==='decorations')setTool('decor_bench');else if(next==='terrain')setTool('forest');else if(next==='transit')setTool('route');else if(next==='delete')setTool('bulldoze');else setTool('inspect');$('tool-panel').hidden=wasOpen;}renderTools();renderDock();}
function renderDock(){$('dock').innerHTML=categories.map(([key,icon,label])=>`<button data-category="${key}" class="${category===key?'active':''}" title="${label}"><b>${icon}</b>${label}</button>`).join('');}
function renderTools(){
  const s=city.s;let html='';
  if(category==='zones')html=title('BUILD YOUR NEIGHBOURHOODS','Homes with a future','Start with houses. Apartment blocks provide more homes without waiting for a metropolitan skyline.')+`<div class="segmented">${[1,2,3,4].map(n=>`<button data-density="${n}" title="${densityGate(s,n)||'Available'}" ${densityGate(s,n)?'disabled':''} class="${density===n?'active':''}">${['Low','Mid','High','Skyline'][n-1]}${densityGate(s,n)?' 🔒':''}</button>`).join('')}</div><div class="tool-grid">${Object.entries(ZONES).map(([k,v])=>toolCard(k,v.name,v.short,Math.round(v.cost*density*DIFFICULTIES[s.difficulty].cost))).join('')}${toolCard('apartments','Apartment block','▥',Math.round(4800*DIFFICULTIES[s.difficulty].cost),'· 2 × 2')}${toolCard('skyscraper','Skyscraper','▤',Math.round(120000*DIFFICULTIES[s.difficulty].cost),'· 4 × 4')}</div><div class="tip">Apartments: up to 240 people, 21 days to build, unlocked at 250 residents. Medium zoning: 750 residents. High: 10,000. Skyscrapers: 4 × 4 tiles, 75,000 people, excellent services, transit and 12 profitable months.</div>`;
  if(category==='roads')html=title('CONNECT THE CITY','Streets & networks','Drag an L-shaped connection. Streets reaching the map edge provide regional access.')+`<div class="tool-grid">${Object.entries(networkTools).map(([k,v])=>toolCard(k,v.name,v.icon,Math.round(v.cost*DIFFICULTIES[s.difficulty].cost),v.days?'· '+v.days+' days':'/ tile')).join('')}</div><div class="tip">${networkTools[tool]?.desc||''} Roads over water become bridges: $480 per street tile, $960 per avenue tile. Rail bridges cost $520.</div>`;
  if(category==='services')html=title('TAKE CARE OF YOUR CITY','Civic campuses','Reserve clear, level land with a street touching any edge of the footprint. Facilities take 3–30 days to open.')+`<div class="tool-grid">${Object.entries(SERVICES).filter(([,v])=>!v.recreation&&!v.decoration).map(([k,v])=>toolCard(k,v.name,v.icon,Math.round(v.cost*DIFFICULTIES[s.difficulty].cost),`· ${v.size} × ${v.size} · ${v.days} days`)).join('')}</div><div class="tip">${SERVICES[tool]?.desc||'Use the overlays to find underserved areas.'}</div>`;
  if(category==='recreation')html=title('PLACES TO PLAY & RELAX','Parks & recreation','Build shared spaces beside a road. Beaches need dry land touching river water. All facilities improve recreation coverage, friendships and land value.')+`<div class="tool-grid">${Object.entries(SERVICES).filter(([,v])=>v.recreation).map(([k,v])=>toolCard(k,v.name,v.icon,Math.round(v.cost*DIFFICULTIES[s.difficulty].cost),`· ${v.size} × ${v.depth||v.size} · ${v.days} days`)).join('')}</div><div class="tip">${SERVICES[tool]?.desc||'Choose a recreation facility.'}</div>`;
  if(category==='decorations')html=title('SMALL DETAILS, MORE CHARACTER','Decorate your city','Place instantly on a clear 1 × 1 lot. No roads, utilities or monthly upkeep required.')+`<div class="tool-grid">${Object.entries(SERVICES).filter(([,v])=>v.decoration).map(([k,v])=>toolCard(k,v.name,v.icon,Math.round(v.cost*DIFFICULTIES[s.difficulty].cost),'· '+(v.season||'All seasons'))).join('')}</div><div class="tip">${SERVICES[tool]?.desc||''}<br>Nearby homes gain +1 happiness from a decoration matching the season or an all-season decoration, plus +2 during holidays. Bonuses do not stack.</div><button class="full" data-action="season-calendar">Season & holiday calendar →</button>`;
  if(category==='terrain')html=title('SHAPE THE REGION','Land & landscape','Drag over empty land. Lower land below sea level to create water; use streets to bridge it.')+`<div class="tool-grid">${Object.entries(terrainTools).map(([k,v])=>toolCard(k,v.name,v.icon,v.cost)).join('')}</div>${range('climate.temperature','Temperature',s.climate.temperature,-20,45,1,'°C')}${range('climate.rain','Rainfall',s.climate.rain,0,100)}<div class="tip">Woodland lowers pollution. Temperature, moisture and the seasons change natural biomes over time.</div>`;
  if(category==='transit'){
    const q=city.quoteRoute(routeMode,routeStops);
    html=title('KEEP PEOPLE MOVING','Plan a line','Select road tiles as stops. Bus and tram routes follow streets; metro tunnels can cross the river.')+`<label class="field">Transport mode<select id="route-mode">${Object.entries(MODES).map(([k,m])=>`<option value="${k}" ${k===routeMode?'selected':''}>${m.name}</option>`).join('')}</select></label><label class="field">Line name<input id="route-name" maxlength="40" placeholder="e.g. Riverside circular" value="${escape(routeName)}"></label><div class="stop-list">${routeStops.map((i,k)=>`<div><span class="route-number">${k+1}</span>${district(i).split(' · ')[1]}</div>`).join('')||'<span class="muted">Click the first stop on a road.</span>'}</div>${q.error?`<p>${escape(q.error)}</p>`:row('Construction quote',money(q.cost))+row('Construction time',q.days+' days')}<div class="inline-buttons"><button data-action="undo-stop">Undo stop</button><button data-action="clear-stops">Clear</button></div><button class="primary full" data-action="open-line" ${q.error?'disabled':''}>Build line</button><button class="full" data-action="transport">Manage transport →</button><div class="tip">Rail stops need adjacent track. Transfers between lines are automatic at shared stops. High fares reduce ridership.</div>`;
  }
  if(category==='overlays')html=title('READ YOUR CITY','Data views','Colour reveals pressure and opportunity. Select a building for precise figures.')+`<div class="overlay-list">${Object.entries(OVERLAYS).map(([k,v])=>`<button class="${world.overlay===k?'active':''}" data-overlay="${k}">${v}</button>`).join('')}</div><div class="tip">Red means a shortage or a problem; green means good conditions. Zoning uses green homes, blue shops and yellow industry.</div>`;
  if(category==='delete')html=title('MAKE ROOM FOR SOMETHING NEW','Delete anything','Click a tile or drag over an area. Choose everything, or just the layer you want to remove.')+`<div class="overlay-list">${Object.entries({all:'Everything',zone:'Zones & buildings',road:'Roads',rail:'Railway',pipe:'Water pipes',powerline:'Power lines',trees:'Trees'}).map(([k,v])=>`<button data-delete-layer="${k}" class="${deleteLayer===k?'active':''}">${v}</button>`).join('')}</div><button class="full" data-action="undo">↶ Undo last change</button><div class="tip">Deletion is free. Removing zoning also removes buildings developed on it. Underground pipes and cables remain unless you select them or choose Everything. Undo is available until the next month.</div>`;
  if(category==='budget')html=title('THE MUNICIPAL TREASURY','Every dollar matters','Taxes, fares and freight fees fund your city. New construction is paid immediately; operations settle each month.')+`<div class="finance-total"><small>AVAILABLE FUNDS</small><b>${money(s.cash)}</b></div>${row('Monthly income',money(s.ledger.income))}${row('Monthly spending',money(s.ledger.expenses))}${row('Outstanding debt',money(s.debt))}<button class="primary full" data-action="budget">Taxes & service funding</button><button class="full" data-action="borrow">Borrow $40,000</button><button class="full" data-action="repay">Repay remaining debt</button><div class="tip">Loans last 60 months. Monthly interest is ${money(s.debt*.005)} at the current loan balance. Repayments are included in spending. Development grants help smaller towns.</div>`;
  if(category==='inspect')html=title('THE MAYOR’S DESK','Know your city','Click a building to inspect its residents, jobs, services and current difficulties.')+`<div class="tool-grid">${toolCard('inspect','Inspect a lot','⌖',0,'')}${toolCard('bulldoze','Delete','⌫',0)}</div><button class="full" data-action="city-report">City overview</button><button class="full" data-action="city">City & saves</button><button class="full" data-action="help">Mayor’s handbook</button><div class="tip">Space pauses time. H hides the interface. F enters full screen. Delete clears the selected lot. Ctrl+Z undoes construction.</div>`;
  $('tool-content').innerHTML=html;
}
function renderTop(){const s=city.s,st=s.stats;$('stats').innerHTML=`<div class="top-stat"><small>TREASURY</small><strong class="${s.cash<0?'negative':''}">${money(s.cash)}</strong><em>${s.ledger.net>=0?'+':''}${money(s.ledger.net)}/mo</em></div><div class="top-stat"><small>RESIDENTS</small><strong>${fmt(st.population)}</strong></div><div class="top-stat"><small>HAPPINESS</small><strong>${st.happiness}<small> /100</small></strong></div><div class="top-stat"><small>JOBS</small><strong>${fmt(st.jobs)}</strong></div>`;
    const date=new Date(Date.UTC(2000,0,1)+s.day*86400000);$('calendar').innerHTML=`${date.toLocaleDateString('en',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'})}<small>${SEASONS[seasonFor(s)].icon} ${seasonFor(s)} · ${city.speed?'Playing':'Paused'}</small>${activeHoliday(s)?`<small class="holiday-now">${activeHoliday(s).icon} ${activeHoliday(s).name}</small>`:''}`;document.querySelectorAll('[data-speed]').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===city.speed));mayorUI.hud();if(s.celebration){const key=s.celebration.name+s.celebration.month;if(key!==lastCelebration){lastCelebration=key;$('celebration').textContent='☆ '+s.celebration.name+' · A new chapter for your city';$('celebration').classList.add('visible');setTimeout(()=>$('celebration').classList.remove('visible'),6000);}}}
const chart=renderHistoryChart;
installChartInteractions();
function renderOverview(){const s=city.s,st=s.stats;let html=title('YOUR CITY AT A GLANCE','The mayor’s report');html+=`<div class="score-block"><div class="score-ring" style="--value:${st.happiness}"><span>${st.happiness}</span></div><div><h3>${st.happiness>=75?'A good place to live':st.happiness>=55?'Finding its feet':'People need support'}</h3><p>Citywide happiness</p></div></div><div class="overview-grid"><div class="mini-stat"><small>UNEMPLOYMENT</small><strong>${pct(st.unemployment)}</strong></div><div class="mini-stat"><small>HOUSING VACANCY</small><strong>${pct(st.vacancy)}</strong></div></div><div class="rule"></div><h3>Development demand</h3>`;
    for(const [k,z] of Object.entries(ZONES)){const d=city.demand[k];html+=`<div class="demand-item">${row(z.name,`${d>0?'+':''}${d}`)}<div class="demand-track"><i style="background:${z.color};left:${d>=0?50:50+d/2}%;width:${Math.abs(d)/2}%"></i></div></div>`;}
    html+=`<p class="footer-note">Positive demand encourages construction. Negative demand means the city already has spare capacity.</p><div class="rule"></div>${row('Average commute',fmt(st.commute)+' min')}${row('Housing cost index',fmt(st.rent))}${row('Land value',fmt(st.land)+' / 100')}<h4>Population over time</h4>${chart(s.history,'population')}<button class="full" data-action="city-report">Residents & milestones →</button>`;
    const next=MILESTONES.find(m=>!s.milestones.includes(m.id));if(next)html+=`<div class="tip"><b>Next milestone · ${next.name}</b><br>${next.desc}. Grant: ${money(next.reward)}.</div>`;
    $('inspector-content').innerHTML=html;
}
const issueHelp={
  'Too few staff':'Build reachable homes or improve road and transit access so residents can fill these jobs.',
  'No power':'Connect this lot to a funded power plant using roads or power lines.',
  'Power capacity exceeded':'Build another power plant or raise electricity funding.',
  'No water':'Connect this lot to funded water works using roads or water pipes.',
  'Water capacity exceeded':'Add water works, raise water funding, or reduce pollution near the pumps.',
  'No road access':'Place a road directly beside the lot and connect it to the rest of the city.',
  'Too few workers':'Zone more homes and connect them to this workplace. Transit helps long trips.',
  'Too few reachable jobs':'Zone workplaces on reachable streets. Check workers can complete the trip.',
  'Commute too long':'Place jobs closer to homes, upgrade congested streets, or add a faster transit line.',
  'Housing costs too high':'Zone more housing or enable affordable housing support in the budget.',
  'Too few customers':'Connect more homes to this shop, or allow demand to catch up.',
  'No freight connection':'Connect roads to a map edge, or build a funded rail terminal with regional track and a freight train.',
  'Waste collection insufficient':'Add reachable recycling capacity or raise waste funding.',
  'High pollution':'Separate homes from heavy industry, add woodland, or adopt clean industry.',
};
function renderInspector(){
  if(selected<0){renderOverview();return;}const s=city.s,t=s.tiles[selected],b=s.buildings.find(b=>b.id===t.building),d=district(selected);
  let html=`<span class="eyebrow">LOT INSPECTOR</span><div class="section-top"><h3>${b?b.service?SERVICES[b.service].name:b.zone==='industrial'?INDUSTRIES[b.industry].name:ZONES[b.zone].name+' building':t.road?t.road===2?'Avenue':'Street':t.rail?'Railway':t.zone?ZONES[t.zone].name+' zone':t.elevation<0?'River':'Undeveloped land'}</h3><button data-action="overview" title="Close inspector">×</button></div><span class="district-label">${d}</span>`;
  if(b){const f=b.info;html+=`<span class="tag ${['abandoned','vacant'].includes(b.status)?'warning':''}">${b.status}</span>${b.zone?` <span class="tag">Density ${b.level} / ${t.density}</span>`:''}<div class="rule"></div>`;
    if(b.status==='construction'){const days=b.service?SERVICES[b.service].days:b.apartment?21:[5,14,24,30][b.targetLevel-1];html+=meter('Construction progress',b.progress)+row('Days of work remaining',Math.ceil((1-b.progress)*days));}if(b.renovationDays)html+=row('Upgrade work remaining',b.renovationDays+' days');
    html+=row('Footprint',`${b.size} × ${b.depth||b.size} tiles`);
    if(b.zone==='residential')html+=`<div class="overview-grid"><div class="mini-stat"><small>${b.apartment?'APARTMENT RESIDENTS':'RESIDENTS'}</small><strong>${b.occupants} / ${capacity(b)}</strong></div><div class="mini-stat"><small>HAPPINESS</small><strong>${f.happiness}</strong></div></div>${row('Employed residents',fmt(f.employed)+' / '+fmt(f.workforce))}${row('Average commute',fmt(f.commute)+' min')}${row('Housing cost / income',money(f.rent)+' / '+money(f.income))}${meter('Affordability',f.affordability)}`;
    if(b.zone&&b.zone!=='residential')html+=row('Workers',fmt(f.workers)+' / '+capacity(b))+row('Available job positions',fmt(f.availableJobs))+row('Customers nearby',fmt(f.customers))+row(b.zone==='commercial'?'Goods supply connection':'Freight connection',f.freight?(f.localSupply&&!f.external&&!f.terminal?'Local suppliers connected':'Connected'):'Unavailable');
    if(b.zone==='industrial')html+=`<label class="field">Industry<select id="industry-select">${Object.entries(INDUSTRIES).map(([k,v])=>`<option value="${k}" ${k===b.industry?'selected':''}>${v.name}</option>`).join('')}</select></label><p>Changing industry costs $500 and clears old inventory.</p>${row('Production chain',`${INDUSTRIES[b.industry].input||'Raw resource'} → ${INDUSTRIES[b.industry].output}`)}${row('Input inventory',fmt(b.inputStock))}${row('Output inventory',fmt(b.stock))}${row('Produced last month',fmt(b.lastProduced))}${row('Exported last month',fmt(b.lastExported))}`;
    if(SERVICES[b.service]?.jobs)html+=row('Staff employed',fmt(f.workers)+' / '+fmt(f.jobCapacity))+row('Funded, operational job positions',fmt(f.availableJobs));
    if(b.service==='education')html+=row('Students enrolled',fmt(f.students)+' / '+fmt(f.capacity))+row('Children waiting for a place',fmt(f.waiting));
    if(b.service==='healthcare')html+=row('Patients treated this month',fmt(f.patients)+' / '+fmt(f.capacity))+row('Patients waiting',fmt(f.waiting));
    if(b.service&&!SERVICES[b.service].decoration)html+=`<p>${SERVICES[b.service].desc}</p>${row('Facility level',(b.upgrade||1)+' / 3')}${row('Operating budget',money(city.serviceBase(b)*s.funding[b.service]/100)+'/mo')}${row('Capacity',fmt(f.capacity))}${row('Reachable demand',fmt(f.use))}${(b.upgrade||1)<3?`<button class="primary full" data-action="upgrade-service">Upgrade · ${money(SERVICES[b.service].cost*.65)}</button>`:''}<button class="full" data-action="budget">Manage service funding</button>`;
    if(SERVICES[b.service]?.decoration)html+=`<p>${SERVICES[b.service].desc}</p>${row('Season',SERVICES[b.service].season||'All seasons')}${row('Monthly upkeep','$0')}<div class="tip">Adds character to nearby homes within five tiles. No road, water or electricity required.</div><button class="full" data-action="rotate-building">Rotate ↻</button>`;
    if(!SERVICES[b.service]?.decoration)html+=`<h4>What this building needs</h4>${f.issues.length?f.issues.map(issue=>`<div class="alert"><b>${escape(issue)}</b>${issueHelp[issue]?`<br><small>${issueHelp[issue]}</small>`:''}</div>`).join(''):'<div class="alert good">All essential needs are being met.</div>'}<h4>Utilities & surroundings</h4>${meter('Electricity',f.power,'#c4a04e')}${meter('Water supply',f.water,'#6aa6b5')}${meter('Waste collection',f.waste)}${row('Land value',fmt(f.land)+' / 100')}${row('Pollution',fmt(f.pollution)+' / 100')}`;
    if(b.zone==='residential')html+=`${row('Decoration happiness','+'+(f.decorationBonus||0))}${row('Holiday happiness','+'+(f.holidayBonus||0))}<h4>Services</h4>${['education','healthcare','police','fire','park'].map(k=>meter(k==='park'?'Parks & recreation':SERVICES[k].name,f[k])).join('')}<h4>Life in this household</h4>${Object.entries(f.person).map(([k,v])=>meter({health:'Health',people:'Relationships',work:'Work & school',rest:'Rest',fun:'Fun'}[k],v/100)).join('')}`;
    if(b.zone)html+=`<h4>Architecture workshop</h4><label class="field">Building style<select id="building-style"><option value="">City style</option>${Object.entries(STYLES).map(([k,v])=>`<option value="${k}" ${k===b.style?'selected':''}>${v.name}</option>`).join('')}</select></label><div class="inline-buttons"><button data-action="rotate-building">Rotate ↻</button><button data-action="variant">New façade</button><button data-action="protect">${b.protected?'Allow redevelopment':'Preserve building'}</button></div>`;
  }else {
    html+=row('Elevation',t.elevation.toFixed(1))+row('Road access',roadAt(s,selected)>=0?'Connected':'No street')+row('Land value',fmt(city.layers.land[selected])+' / 100')+row('Pollution',fmt(city.layers.pollution[selected])+' / 100');
    if(t.road)html+=row('Traffic load',fmt(city.nextTraffic[selected])+' / '+(t.road===2?180:65))+`<p>Regional access comes from continuous roads reaching a map edge. Roads also contain power cables and water mains.</p>`;
    if(t.zone){const pc=city.powerGrid.at(selected),wc=city.waterGrid.at(selected);const reasons=[];if(roadAt(s,selected)<0)reasons.push('Needs a street directly beside this lot.');if(pc<0||city.powerGrid.supply[pc]<=city.powerGrid.need[pc])reasons.push('Needs spare electricity capacity.');if(wc<0||city.waterGrid.supply[wc]<=city.waterGrid.need[wc])reasons.push('Needs spare water capacity.');if(city.demand[t.zone]<5)reasons.push('Demand is currently too low.');html+=row('Density permission',t.density)+row('Current demand',city.demand[t.zone])+`<div class="tip">${reasons.length?reasons.join('<br>'):'Ready for development. Developers choose eligible lots each month; unpause time to start construction.'}</div>`;}
    html+=`<button class="full" data-action="zone-selected">Plan this neighbourhood →</button>`;
  }
  const layers=[['zone','Zones & buildings',t.zone],['road','Road',t.road],['rail','Railway',t.rail],['pipe','Water pipe',t.pipe],['powerline','Power line',t.powerline],['trees','Trees',t.type===2]].filter(([, , exists])=>exists);
  if(t.construction)html+=row('Construction',t.construction.remaining+' day'+(t.construction.remaining===1?'':'s')+' remaining');
  if(b||layers.length||t.construction)html+=`<div class="rule"></div><button class="danger full delete-lot" data-action="delete-selected">⌫ Delete everything on this lot</button>${layers.length?`<div class="inline-buttons">${layers.map(([k,label])=>`<button class="danger" data-delete-selected="${k}">Delete ${label.toLowerCase()}</button>`).join('')}</div>`:''}<button class="full" data-action="undo">↶ Undo last change</button>`;
  $('inspector-content').innerHTML=html;
}
function showModal(html){$('modal-content').innerHTML=html;if(!$('modal').open)$('modal').showModal();}
const mayorUI=createMayorUI({city,getWorld:()=>world,$,row,title,showModal,escape,fmt});
function renderBudget(){mayorUI.budget();}
function renderRegion(){mayorUI.region(selectedParcel);}
function renderProjects(){mayorUI.projects();}

function renderTransport(){const s=city.s;showModal(`${title('THE TRANSPORT AUTHORITY','A connected city','Fare revenue is collected once at the destination, including journeys with transfers.')}<div class="modal-grid"><section>${range('fare','Passenger fare',s.fare,0,12,1,' dollars')}${row('Total completed journeys',fmt(s.delivered))}${row('Passengers lost',fmt(s.lostPassengers))}<h4>Freight railway</h4><p>Build a terminal beside roads and railway. Track must reach a map edge. Trains share terminal throughput and carry exports and mail.</p>${row('Freight trains',s.freightTrains)}${row('Capacity / train',240+' units per month')}${row('Total exported',fmt(s.exported))}${row('Mail handled last month',fmt(s.ledger.mail))}<div class="modal-actions"><button data-action="buy-freight">Buy train · $8,000</button><button data-action="sell-freight">Delete train · +$4,000</button></div><div class="tip">Raw resources → mills and factories → shops or regional exports. Freight handling fees enter the same treasury as taxes and fares.</div><button class="primary full" data-action="plan-line">Plan another passenger line</button></section><section><h3>Your lines</h3>${s.routes.length?s.routes.map(r=>{const info=city.network.routeInfo.get(r.id);return `<div class="route-card" style="--route:${MODES[r.mode].color}"><h4>${escape(r.name)}</h4><p>${MODES[r.mode].name} · ${r.stops.length} stops · ${r.vehicles} vehicle${r.vehicles===1?'':'s'}</p><span class="tag ${info.valid?'':'warning'}">${r.constructionDays?'Under construction · '+r.constructionDays+' days left':!info.valid?'Route disconnected':info.operating?'Operating':'Suspended'}</span>${row('Seat capacity',fmt(info.capacity/2)+' return trips')}${row('Riders last month',fmt(r.riders))}${row('Waiting demand',fmt(r.waiting))}${row('Fare income',money(r.income))}<div class="inline-buttons"><button data-route="${r.id}" data-manage="add">+ Vehicle</button><button data-route="${r.id}" data-manage="remove">Delete vehicle</button><button data-route="${r.id}" data-manage="toggle" ${r.constructionDays?'disabled':''}>${r.active?'Suspend':'Resume'}</button><button class="danger" data-route="${r.id}" data-manage="close">Delete line</button></div></div>`;}).join(''):'<div class="tip">No lines yet. Choose Transport, then click at least two road stops.</div>'}</section></div>`);}
function renderCityReport(){const s=city.s;showModal(`${title('PEOPLE MAKE A CITY','Life in '+escape(s.name))}<div class="modal-grid"><section><h3>City wellbeing</h3>${Object.entries(s.stats.cityValues).map(([k,v])=>meter({jobs:'Jobs',housing:'Housing',education:'Education',healthcare:'Healthcare',safety:'Safety'}[k],v/100)).join('')}<p class="footer-note">Based on the city happiness model. The weakest category matters. Individual health, relationships, work, rest and fun are combined at each residential building.</p><h4>Population</h4>${chart(s.history,'population')}<h4>Monthly balance</h4>${chart(s.history,'net')}<h4>Milestones</h4>${MILESTONES.map(m=>`<div class="milestone"><b>${s.milestones.includes(m.id)?'✓':'○'} ${m.name}</b><p>${m.desc} · ${money(m.reward)}</p></div>`).join('')}</section><section><h3>City notices</h3><div class="tip"><b>${currentEvent(s).name}</b><br>${currentEvent(s).text}</div>${s.news.length?s.news.map(n=>`<div class="news-item"><small>Month ${n.month+1}</small>${escape(n.text)}</div>`).join(''):'<p class="footer-note">Your city’s story will appear here as it grows.</p>'}</section></div>`);}
function renderCity(){showModal(`${title('A CITY OF YOUR MAKING','Your city, your character')}<div class="modal-grid"><section><label class="field">City name<input id="rename-city" value="${escape(city.s.name)}" maxlength="60"></label><label class="field">Architectural character<select id="city-style"><option value="mixed">Mixed neighbourhoods</option>${Object.entries(STYLES).map(([k,v])=>`<option value="${k}" ${city.s.style===k?'selected':''}>${v.name}</option>`).join('')}</select></label><button class="primary full" data-action="save">Save on this device</button><div class="modal-actions"><button data-action="export">Export city JSON</button><button data-action="import">Import city</button><button data-action="screenshot">Save city picture</button><button data-action="export-model">Export city GLB</button></div><p class="footer-note">Autosaves at the end of each month. Export a city file to move between browsers or keep a backup.</p></section><section><h3>A new beginning</h3><p>Start a new city. Your current city is backed up on this device before replacement.</p><label class="field">Map seed<input id="new-seed" type="number" min="0" max="4294967295" value="${city.s.seed+1}"></label><label class="field">Difficulty<select id="new-difficulty">${Object.entries(DIFFICULTIES).map(([k,d])=>`<option value="${k}" ${k===city.s.difficulty?'selected':''}>${d.name}</option>`).join('')}</select></label><label class="field">Scenario<select id="new-scenario">${Object.entries(SCENARIOS).map(([k,d])=>`<option value="${k}">${d.name}</option>`).join('')}</select></label><button class="full" data-action="new-starter">New starter neighbourhood</button><button class="full" data-action="new-empty">New empty region</button><button class="full" data-action="restore-backup">Restore previous city</button><div class="tip">Starting capital depends on difficulty. Your initial four parcels provide room for a small town. Build a road to the edge, add power and water, then zone homes and workplaces.</div></section></div>`);}
function renderHelp(){showModal(`${title('THE MAYOR’S HANDBOOK','A city is a thousand decisions.')}<div class="modal-grid handbook"><section><h3>Your first neighbourhood</h3><ol><li>Draw streets. Connect one to the map edge for trade.</li><li>Place a power plant and water works beside a connected road. Streets contain utility ducts.</li><li>Zone homes, shops and industry along the street frontage. Start with low density.</li><li>Press Play. Every day lasts 7.5 seconds at normal speed. The calendar advances daily and finances settle at month-end. Developers need demand, utilities and access.</li><li>Add services as the population grows. A reachable hospital can still run out of capacity.</li></ol><h3>Growth and renewal</h3><p>Higher zoning density allows redevelopment after twelve healthy months; skyscrapers require twenty-four. Vacant buildings can become abandoned after twelve struggling months. Restoring connections and demand allows redevelopment. Preserve a building to prevent density upgrades.</p><h3>Affordability</h3><p>Education, parks and good services raise land value and household income. Scarce attractive housing pushes up rent. Build more homes or fund housing support to keep residents.</p></section><section><h3>Move people and goods</h3><p>Homes need jobs reachable within 55 travel minutes. Congestion slows streets and buses. Trams and metro provide faster travel; shared stops allow transfers. A single fare is paid per completed trip. Fleet seats and funding limit throughput.</p><p>Industrial lots produce resources or turn inputs into finished products. Connect factories and shops with roads. Roads to map edges allow limited trade. Railway exports need a connected terminal and a freight train.</p><h3>Build controls</h3><ul><li><span class="kbd">F</span> full screen · <span class="kbd">H</span> hide interface</li><li><span class="kbd">Delete</span> clear the selected lot, including zoning</li><li><span class="kbd">Left drag</span> zone rectangles or draw networks</li><li><span class="kbd">Right drag</span> pan · <span class="kbd">Wheel</span> zoom</li><li><span class="kbd">Middle drag</span> orbit · <span class="kbd">Q / E</span> rotate</li><li><span class="kbd">W A S D</span> pan · <span class="kbd">Home</span> reset camera</li><li><span class="kbd">Space</span> pause · <span class="kbd">Esc</span> inspect</li><li><span class="kbd">Ctrl+S</span> save · <span class="kbd">Ctrl+Z</span> undo construction</li></ul><p>On a touch screen, tap to place individual tiles and use two fingers to move or zoom. To zone a larger area, use a mouse.</p></section></div>`);}
function download(data,name,type='application/json'){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function refresh(){city.analyse();city.revision++;lastUI=-1;}
function newCity(starter,seed){try{localStorage.setItem(SAVE_KEY+'.backup',city.export());}catch{}city.replace(createState(seed,starter,$('new-difficulty')?.value||city.s.difficulty,$('new-scenario')?.value||'revival'));selected=-1;routeStops=[];world.routeDraft=[];world.home();$('modal').close();setCategory('zones');toast('Your new city is ready. Start planning, then press Play.');}
document.addEventListener('click',async event=>{
  const button=event.target.closest('button');if(button&&handleChartClick(button))return;if(!button)return;
  if(button.dataset.category){setCategory(button.dataset.category);return;}
  if(button.dataset.parcel){selectedParcel=Number(button.dataset.parcel);renderRegion();return;}
  if(button.dataset.buyParcel){toast(city.buyLand(Number(button.dataset.buyParcel)));renderRegion();lastUI=-1;return;}
  if(button.dataset.districtParcel){toast(city.setDistrict(Number(button.dataset.districtParcel),$('district-choice').value));renderRegion();lastUI=-1;return;}
  if(button.dataset.focusParcel){const p=parcelXY(Number(button.dataset.focusParcel));$('modal').close();world.focus(index(p.x*PARCEL+9,p.z*PARCEL+9));return;}
  if(button.dataset.paperLot!==undefined){selected=Number(button.dataset.paperLot);$('modal').close();world.focus(selected,1.4);world.select(selected);$('tool-panel').hidden=true;$('inspector').hidden=false;renderInspector();return;}
  if(button.dataset.request){selected=Number(button.dataset.request);$('modal').close();world.focus(selected,1.4);world.setOverlay(button.dataset.requestOverlay);world.select(selected);$('inspector').hidden=false;renderInspector();return;}
  if(button.dataset.offer){toast(respondOffer(city,button.dataset.offer==='accept'));renderProjects();lastUI=-1;return;}
  if(button.dataset.tool){setTool(button.dataset.tool);return;}
  if(button.dataset.density){const gate=densityGate(city.s,Number(button.dataset.density));if(gate)toast(gate);else density=Number(button.dataset.density);renderTools();return;}
  if(button.dataset.deleteLayer){deleteLayer=button.dataset.deleteLayer;renderTools();return;}
  if(button.dataset.deleteSelected){toast(city.remove([selected],button.dataset.deleteSelected));renderInspector();lastUI=-1;return;}
  if(button.dataset.speed){city.speed=Number(button.dataset.speed);renderTop();return;}
  if(button.dataset.overlay){world.setOverlay(button.dataset.overlay);renderTools();const name=world.overlay;$('legend').hidden=name==='none';$('legend').innerHTML=name==='zones'?'<b>Zoning</b><p>🟩 Homes · 🟦 Shops · 🟨 Industry</p>':`<b>${OVERLAYS[name]}</b><div class="gradient"></div><div class="legend-labels"><span>${['traffic','pollution'].includes(name)?'High pressure':'Low / unavailable'}</span><span>${['traffic','pollution'].includes(name)?'Low pressure':'High / supplied'}</span></div>`;return;}
  if(button.dataset.manage){toast(city.manageRoute(Number(button.dataset.route),button.dataset.manage));renderTransport();return;}
  const b=city.buildingsById.get(city.s.tiles[selected]?.building);
  switch(button.dataset.action){
    case 'overview':selected=-1;world.select(-1);$('inspector').hidden=true;renderOverview();break;
    case 'close-tools':$('tool-panel').hidden=true;break;
    case 'delete-selected':if(selected>=0){toast(city.remove([selected]));renderInspector();}break;
    case 'undo':toast(city.undo());break;
    case 'toggle-interface':toggleInterface();break;
    case 'fullscreen':toggleFullscreen();break;
    case 'zone-selected':setCategory('zones');break;
    case 'home':world.home();break;
    case 'rotate-left':world.rotate(-Math.PI/2);break;
    case 'rotate-right':world.rotate(Math.PI/2);break;
    case 'night':world.night();break;
    case 'help':renderHelp();break;
    case 'budget':renderBudget();break;
    case 'transport':renderTransport();break;
    case 'city-report':renderCityReport();break;
    case 'projects':renderProjects();break;
    case 'newspaper':showModal(renderNewspaper(city.s,escape));break;
    case 'region':renderRegion();break;
    case 'city':renderCity();break;
    case 'close-modal':$('modal').close();break;
    case 'save':city.save();break;
    case 'borrow':toast(city.borrow());if($('modal').open)renderBudget();renderTools();break;
    case 'repay':toast(city.repay());if($('modal').open)renderBudget();renderTools();break;
    case 'undo-stop':routeStops.pop();world.revision=-1;renderTools();break;
    case 'clear-stops':routeStops.length=0;world.revision=-1;renderTools();break;
    case 'open-line':{const count=city.s.routes.length;toast(city.addRoute(routeMode,routeStops,routeName));if(city.s.routes.length>count){routeStops.length=0;routeName='';}renderTools();break;}
    case 'plan-line':$('modal').close();setCategory('transit');break;
    case 'buy-freight':if(city.s.freightTrains>=20)toast('Maximum 20 freight trains.');else if(city.s.cash>=8000){city.checkpoint();city.spend(8000);city.s.freightTrains++;refresh();toast('Freight locomotive purchased.');}else toast('Not enough funds for a locomotive.');renderTransport();break;
    case 'sell-freight':if(city.s.freightTrains){city.checkpoint();city.s.freightTrains--;city.s.cash+=4000;refresh();}renderTransport();break;
    case 'season-calendar':showModal(calendarHTML(city.s));break;
    case 'open-decorations':$('modal').close();setCategory('decorations');break;
    case 'upgrade-service':if(b)toast(city.upgradeService(b.id));break;
    case 'rotate-building':if(b){city.checkpoint();b.rotation=(b.rotation+Math.PI/2)%(Math.PI*2);refresh();}break;
    case 'variant':if(b){city.checkpoint();b.design=(b.design+1)%7;refresh();}break;
    case 'protect':if(b){b.protected=!b.protected;refresh();}break;
    case 'export':download(city.export(),`${city.s.name.replace(/[^a-z0-9]/gi,'-')}.rivergate.json`);toast('City exported.');break;
    case 'import':$('import-file').click();break;
    case 'screenshot':{world.renderer.render(world.scene,world.camera);world.canvas.toBlob(blob=>{if(blob)download(blob,'rivergate-city.png','image/png');});break;}
    case 'export-model':{toast('Preparing the city model…');try{const {GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');const result=await new GLTFExporter().parseAsync(world.scene,{binary:true,onlyVisible:true});download(result,'rivergate-city.glb','model/gltf-binary');toast('City model exported.');}catch{toast('The city model could not be exported. Your saved city is unchanged.');}break;}
    case 'new-starter':case 'new-empty':newCity(button.dataset.action==='new-starter',Math.floor(clamp(Number($('new-seed').value)||74021,0,4294967295)));break;
    case 'restore-backup':try{const raw=localStorage.getItem(SAVE_KEY+'.backup');if(!raw)throw new Error('No previous city is available.');city.replace(validateSave(JSON.parse(raw)));selected=-1;routeStops=[];world.routeDraft=[];$('modal').close();toast('Previous city restored.');}catch(e){toast(e.message);}break;
  }
  lastUI=-1;
});
document.addEventListener('input',event=>{
  const el=event.target;if(el.id==='route-name')routeName=el.value;
  if(el.dataset.money){const output=el.closest('label')?.querySelector('output');if(output)output.textContent=money(Number(el.value))+' / month';}
  if(el.dataset.setting){const output=el.closest('label')?.querySelector('output');if(output)output.textContent=el.value+(el.dataset.setting==='fare'?' dollars':el.dataset.setting==='climate.temperature'?'°C':'%');}
});
document.addEventListener('change',event=>{
  const el=event.target,s=city.s,b=s.buildings.find(b=>b.i===selected);
  if(el.dataset.money){const [group,key]=el.dataset.money.split('.'),base=city.financeBase(group,key);if(base>0)s[group][key]=clamp(Number(el.value)/base,0,group==='taxes'?20:150);refresh();const output=el.closest('label')?.querySelector('output');if(output)output.textContent=money(base*s[group][key])+' / month';}
  if(el.dataset.setting){const [group,key]=el.dataset.setting.split('.');if(key)s[group][key]=Number(el.value);else s[group]=Number(el.value);refresh();}
  if(el.dataset.policy){s.policies[el.dataset.policy]=el.checked;refresh();if($('modal').open)renderBudget();}
  if(el.id==='route-mode'){routeMode=el.value;renderTools();}
  if(el.id==='rename-city'){s.name=el.value.trim().slice(0,60)||'Rivergate';refresh();}
  if(el.id==='city-style'){s.style=el.value;refresh();}
  if(el.id==='building-style'&&b){b.style=el.value||null;refresh();}
  if(el.id==='industry-select'&&b&&INDUSTRIES[el.value]){if(city.spend(500)){b.industry=el.value;b.stock=0;b.inputStock=0;refresh();}else {el.value=b.industry;toast('Not enough funds to convert this industry.');}}
});
$('import-file').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>8e6)throw new Error('This file is too large for a city save.');const parsed=validateSave(JSON.parse(await file.text()));try{localStorage.setItem(SAVE_KEY+'.backup',city.export());}catch{}city.replace(parsed);selected=-1;routeStops=[];world.routeDraft=[];$('modal').close();toast('City imported. Time is paused.');}catch(e){toast(e.message||'This city file could not be read.');}finally{event.target.value='';}});
function cellsFor(a,b){if(['apartments','skyscraper'].includes(tool))return [b];return SERVICES[tool]||tool==='inspect'||tool==='route'?[b]:['road','avenue','rail','powerline','pipe'].includes(tool)?lineCells(a,b):rectCells(a,b);}
function pointerMove(event){if(!world)return;hovered=world.pick(event);const bubble=$('context-bubble');if(hovered<0){world.setHover([]);bubble.hidden=true;return;}const {x,z}=xy(hovered);$('coordinates').textContent=`${x+1}, ${z+1} · ${district(hovered).split(' · ')[0]}`;bubble.style.left=Math.min(event.clientX+20,innerWidth-245)+'px';bubble.style.top=Math.max(85,Math.min(event.clientY+20,innerHeight-120))+'px';if(tool==='inspect'){world.setHover([]);const b=city.buildingsById.get(city.s.tiles[hovered]?.building);bubble.hidden=!b||immersive;if(b)bubble.innerHTML=`<b>${b.service?SERVICES[b.service].name:b.zone==='industrial'?INDUSTRIES[b.industry].name:b.level===4?'Skyscraper':b.apartment?'Apartment block':ZONES[b.zone].name}</b><span>${b.info.issues.find(i=>i!=='Under construction')||'Feeling at home'} · Click to explore</span>`;return;}const cells=cellsFor(dragStart>=0?dragStart:hovered,hovered);world.setHover(SERVICES[tool]||['apartments','skyscraper'].includes(tool)?footprint(hovered,SERVICES[tool]?.size||(tool==='skyscraper'?4:2),SERVICES[tool]?.depth||SERVICES[tool]?.size||(tool==='skyscraper'?4:2)):cells,tool==='bulldoze'?'#de8d74':ZONES[tool]?.color||'#b6efff');if(tool!=='route'){const q=city.edit(tool,cells,{density,deleteLayer,quote:true});bubble.hidden=immersive;bubble.innerHTML=typeof q==='string'?`<span>${escape(q)}</span>`:`<b>${q.cells.length||q.count} tile${(q.cells.length||q.count)===1?'':'s'} · ${money(q.cost)}</b><span>${q.cost>city.s.cash?'Not enough funds':q.days?q.days+' days to open':dragStart>=0?'Release to build':'Click or drag to build'}</span>`;}else bubble.hidden=true;}
function place(i){if(i<0)return;if(tool==='inspect'){selected=city.buildingsById.get(city.s.tiles[i].building)?.i??i;selectedParcel=parcelOf(selected);world.select(selected);$('tool-panel').hidden=true;$('inspector').hidden=false;renderInspector();return;}if(tool==='route'){if(!city.s.tiles[i].road){toast('Place stops on road tiles.');return;}if(routeStops.includes(i)){toast('This stop is already on the line.');return;}if(routeStops.length>=12){toast('Maximum twelve stops per line.');return;}routeStops.push(i);world.routeDraft=routeStops;world.revision=-1;renderTools();return;}toast(city.edit(tool,cellsFor(dragStart>=0?dragStart:i,i),{density,deleteLayer}));lastUI=-1;}
document.addEventListener('keydown',event=>{
  if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)||$('modal').open||$('welcome').open||!world)return;
  if(event.code==='KeyH'){event.preventDefault();toggleInterface();}
  else if(event.code==='KeyF'){event.preventDefault();toggleFullscreen();}
  else if(event.key==='Delete'){event.preventDefault();if(selected>=0){toast(city.remove([selected]));lastUI=-1;}else setCategory('delete');}
  else if(event.code==='Space'){event.preventDefault();city.speed=city.speed?0:1;renderTop();}
  else if(event.key==='Escape'){dragStart=-1;setCategory('inspect');world.setHover([]);}
  else if(event.ctrlKey&&event.key.toLowerCase()==='s'){event.preventDefault();city.save();}
  else if(event.ctrlKey&&event.key.toLowerCase()==='z'){event.preventDefault();toast(city.undo());lastUI=-1;}
  else if(event.key.toLowerCase()==='q')world.rotate(-Math.PI/2);
  else if(event.key.toLowerCase()==='e')world.rotate(Math.PI/2);
  else if(event.key==='Home')world.home();
  else if(['w','a','s','d'].includes(event.key.toLowerCase())){const k=event.key.toLowerCase();world.pan(k==='a'?-12:k==='d'?12:0,k==='w'?-12:k==='s'?12:0);}
});
function start(mode){if(mode==='saved'&&!city.load()){toast('No saved city could be loaded.');return;}if(mode!=='saved')city.replace(createState(74021,mode!=='empty',$('start-difficulty').value,mode==='empty'?'sandbox':$('start-scenario').value));world.home();$('welcome').close();setCategory('inspect');renderTop();renderInspector();toast('Your city, wide open. Choose a tool below or click a building. Space starts time.');}
$('start-starter').onclick=()=>start('starter');$('start-empty').onclick=()=>start('empty');$('continue-city').onclick=()=>start('saved');
try{$('continue-city').disabled=!(localStorage.getItem(SAVE_KEY)||localStorage.getItem('rivergate.city.v1'));}catch{$('continue-city').disabled=true;}
async function boot(){
  try{world=new World($('city-canvas'),city);}catch{ $('loading').innerHTML='<div><h2>Your browser could not start the 3D view.</h2><p>Enable hardware acceleration and reopen Rivergate in a WebGL-capable browser.</p></div>';return;}
  const canvas=$('city-canvas');canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointermove',pointerMove);
  canvas.addEventListener('pointerdown',event=>{if(event.button!==0||$('modal').open||$('welcome').open)return;if(event.pointerType==='touch'){touchStart={x:event.clientX,y:event.clientY,time:performance.now()};return;}dragStart=world.pick(event);if(dragStart>=0)canvas.setPointerCapture(event.pointerId);});
  canvas.addEventListener('pointerup',event=>{if(event.button!==0)return;if(event.pointerType==='touch'){if(touchStart&&Math.hypot(event.clientX-touchStart.x,event.clientY-touchStart.y)<8&&performance.now()-touchStart.time<400)place(world.pick(event));touchStart=null;return;}const hit=world.pick(event);if(dragStart>=0)place(hit);dragStart=-1;world.setHover([]);});
  canvas.addEventListener('pointercancel',()=>{dragStart=-1;touchStart=null;world.setHover([]);});canvas.addEventListener('pointerleave',()=>{$('context-bubble').hidden=true;if(dragStart<0)world.setHover([]);});
  renderDock();renderTools();renderTop();renderInspector();let last=performance.now();
  function frame(now){const dt=(now-last)/1000;last=now;city.tick(dt);world.draw(dt);if(lastUI!==city.revision){renderTop();renderInspector();if(['budget','zones'].includes(category))renderTools();lastUI=city.revision;}requestAnimationFrame(frame);}requestAnimationFrame(frame);
  const failures=await world.load((n,total)=>$('loading-progress').textContent=`Preparing buildings and vehicles · ${n} / ${total}`);ready=true;$('loading').hidden=true;$('welcome').showModal();if(failures.length)toast(`${failures.length} models could not load. Simple building forms are available; reopen the game to retry.`);
}
$('region-map').addEventListener('click',event=>{const rect=event.currentTarget.getBoundingClientRect(),x=Math.floor((event.clientX-rect.left)/rect.width*N),z=Math.floor((event.clientY-rect.top)/rect.height*N);world.focus(index(x,z),1);});
boot();
